export const themes = {
  dark: {
    name: 'dark',
    sidebar: {
      bg: 'bg-slate-900',
      text: 'text-slate-300',
      textWhite: 'text-white',
      textMuted: 'text-slate-400',
      border: 'border-slate-800',
      borderLight: 'border-slate-700',
      inputBg: 'bg-slate-800',
      inputBorder: 'border-slate-700',
      inputText: 'text-white',
      inputPlaceholder: 'placeholder-slate-500',
      buttonActive: 'bg-slate-700 border-slate-500',
      buttonInactive: 'bg-slate-800 border-slate-700 opacity-50 hover:bg-slate-700',
      statCardBg: 'bg-slate-800',
      statCardBorder: 'border-slate-700',
      statCardTotal: 'bg-slate-700 border-slate-600',
      sectionBg: 'bg-slate-900/50',
    },
    main: {
      bg: 'bg-slate-950',
      text: 'text-slate-200',
      textMuted: 'text-slate-500',
      textSecondary: 'text-slate-400',
    },
    header: {
      bg: 'bg-slate-900',
      text: 'text-slate-100',
      border: 'border-slate-800',
      buttonBg: 'bg-slate-800',
      buttonBorder: 'border-slate-700',
      buttonText: 'text-slate-200',
      buttonHover: 'hover:bg-slate-700',
    },
    banner: {
      bg: 'bg-slate-900',
      cardBg: 'bg-slate-800',
      cardBorder: 'border-slate-700',
      text: 'text-slate-100',
      textMuted: 'text-slate-400',
      textSecondary: 'text-slate-300',
      iconBg: 'bg-slate-700',
    },
    card: {
      bg: 'bg-slate-800',
      border: 'border-slate-700',
      text: 'text-slate-100',
      textMuted: 'text-slate-400',
      textSecondary: 'text-slate-300',
      contentBg: 'bg-slate-700/50',
      contentBorder: 'border-slate-600',
      participantBg: 'bg-slate-700',
      participantBorder: 'border-slate-600',
    },
    timeline: {
      line: 'bg-slate-700',
      endText: 'text-slate-500',
      emptyBorder: 'border-slate-600',
      emptyText: 'text-slate-400',
    },
    dropdown: {
      bg: 'bg-slate-800',
      border: 'border-slate-700',
      text: 'text-slate-200',
      hover: 'hover:bg-slate-700',
      active: 'bg-indigo-900/50 text-indigo-400',
    },
  },
  light: {
    name: 'light',
    sidebar: {
      bg: 'bg-slate-900',
      text: 'text-slate-300',
      textWhite: 'text-white',
      textMuted: 'text-slate-400',
      border: 'border-slate-800',
      borderLight: 'border-slate-700',
      inputBg: 'bg-slate-800',
      inputBorder: 'border-slate-700',
      inputText: 'text-white',
      inputPlaceholder: 'placeholder-slate-500',
      buttonActive: 'bg-slate-700 border-slate-500',
      buttonInactive: 'bg-slate-800 border-slate-700 opacity-50 hover:bg-slate-700',
      statCardBg: 'bg-slate-800',
      statCardBorder: 'border-slate-700',
      statCardTotal: 'bg-slate-700 border-slate-600',
      sectionBg: 'bg-slate-900/50',
    },
    main: {
      bg: 'bg-slate-50',
      text: 'text-slate-800',
      textMuted: 'text-slate-500',
      textSecondary: 'text-slate-600',
    },
    header: {
      bg: 'bg-white',
      text: 'text-slate-800',
      border: 'border-slate-200',
      buttonBg: 'bg-white',
      buttonBorder: 'border-slate-300',
      buttonText: 'text-slate-700',
      buttonHover: 'hover:bg-slate-50',
    },
    banner: {
      bg: 'bg-slate-50',
      cardBg: 'bg-white',
      cardBorder: 'border-slate-200',
      text: 'text-slate-800',
      textMuted: 'text-slate-400',
      textSecondary: 'text-slate-600',
      iconBg: 'bg-indigo-50',
    },
    card: {
      bg: 'bg-white',
      border: 'border-slate-200',
      text: 'text-slate-800',
      textMuted: 'text-slate-500',
      textSecondary: 'text-slate-600',
      contentBg: 'bg-slate-50/50',
      contentBorder: 'border-slate-100',
      participantBg: 'bg-slate-50',
      participantBorder: 'border-slate-100',
    },
    timeline: {
      line: 'bg-slate-200',
      endText: 'text-slate-400',
      emptyBorder: 'border-slate-300',
      emptyText: 'text-slate-500',
    },
    dropdown: {
      bg: 'bg-white',
      border: 'border-slate-200',
      text: 'text-slate-700',
      hover: 'hover:bg-slate-100',
      active: 'bg-indigo-50 text-indigo-600',
    },
  },
};

export const channelColors = {
  phone: { bg: 'bg-blue-100', text: 'text-blue-600', border: 'border-blue-200', icon: 'text-blue-400' },
  bt: { bg: 'bg-orange-100', text: 'text-orange-600', border: 'border-orange-200', icon: 'text-orange-400' },
  qtrade: { bg: 'bg-teal-100', text: 'text-teal-600', border: 'border-teal-200', icon: 'text-teal-400' },
  ideal: { bg: 'bg-indigo-100', text: 'text-indigo-600', border: 'border-indigo-200', icon: 'text-indigo-400' },
  email: { bg: 'bg-slate-100', text: 'text-slate-600', border: 'border-slate-200', icon: 'text-slate-400' },
  meeting: { bg: 'bg-purple-100', text: 'text-purple-600', border: 'border-purple-200', icon: 'text-purple-400' },
};

export const riskColors = {
  high: { bg: 'bg-rose-50', text: 'text-rose-700', badgeBg: 'bg-rose-100', border: 'border-rose-200', line: 'bg-rose-500', dot: 'bg-rose-500' },
  medium: { bg: 'bg-amber-50', text: 'text-amber-700', badgeBg: 'bg-amber-100', border: 'border-amber-200', line: 'bg-amber-500', dot: 'bg-amber-500' },
  low: { bg: 'bg-emerald-50', text: 'text-emerald-700', badgeBg: 'bg-emerald-100', border: 'border-emerald-200', line: 'bg-emerald-500', dot: 'bg-emerald-500' },
};

export const indicatorColors = {
  danger: { bg: 'bg-rose-50', text: 'text-rose-700', border: 'border-rose-200' },
  warning: { bg: 'bg-amber-50', text: 'text-amber-700', border: 'border-amber-200' },
  info: { bg: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200' },
};
